name: Language Change Proposals
description: Changes to the language
labels: ["Proposal", "v2", "LanguageChange"]
title: "proposal: Go 2: "


body:
  - type: markdown
    attributes:
      value: |
       Our process for evaluating language changes can be found here: https://go.googlesource.com/proposal/+/refs/heads/master#language-changes

  - type: dropdown
    id: author-go-experience
    attributes:
      label: "Go Programming Experience"
      description: "Would you consider yourself a novice, intermediate, or experienced Go programmer?"
      options:
        - "Novice"
        - "Intermediate"
        - "Experienced"
      default: 1

  - type: input
    id: author-other-languages-experience
    attributes:
      label: "Other Languages Experience"
      description: "What other languages do you have experience with?"
      placeholder: "Go, Python, JS, Rust"
    validations:
      required: false

#  - type: dropdown
#    id: other-languages
#    attributes:
#      label: "Other Languages Experience"
#      description: "What other languages do you have experience with?"
#      options:
#        - "Java"
#        - "Python"
#        - "C++"
#        - "Other (please specify)"
#

  - type: dropdown
    id: related-idea
    attributes:
      label: "Related Idea"
      description: "Has this idea, or one like it, been proposed before?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: related-proposals
    attributes:
      label: "Related proposals"
      description: "Has this idea, or one like it, been proposed before? If so, how does this proposal differ? Does this affect error handling? If so, how does this differ from previous error handling proposals? Is this about generics? If so, how does this relate to the accepted design and other generics proposals?"
    validations:
      required: false
#
#  - type: textarea
#    id: proposal
#    attributes:
#      label: "Proposal"
#      description: "What is the proposed change? Who does this proposal help, and why? Please describe as precisely as possible the change to the language. What would change in the language spec? Please also describe the change informally, as in a class teaching Go. Is this change backward compatible? Breaking the Go 1 compatibility guarantee is a large cost and requires a large benefit. Show example code before and after the change. Orthogonality: how does this change interact or overlap with existing features? Is the goal of this change a performance improvement? If so, what quantifiable improvement should we expect? How would we measure it?"
#    validations:
#      required: true
#
#  - type: textarea
#    id: costs
#    attributes:
#      label: "Costs"
#      description: "Would this change make Go easier or harder to learn, and why? What is the cost of this proposal? (Every language change has a cost). How many tools (such as vet, gopls, gofmt, goimports, etc.) would be affected? What is the compile time cost? What is the run time cost? Can you describe a possible implementation? Do you have a prototype? (This is not required.)"
#    validations:
#      required: false
